import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const mem=new Map();
const localStorage={getItem:k=>mem.has(k)?mem.get(k):null,setItem:(k,v)=>mem.set(k,String(v)),removeItem:k=>mem.delete(k)};
const ctx={window:{},localStorage,console,Date,JSON,Set,Map};ctx.window.window=ctx.window;vm.createContext(ctx);
vm.runInContext(fs.readFileSync(new URL('../assets/js/modules/talent/application-dossier-v45.js',import.meta.url),'utf8'),ctx,{filename:'application-dossier-v45.js'});
const D=ctx.window.LutminDossierV45;
assert(D,'dossier api no disponible');
const a=D.upsertExternal({title:'Supervisor de mantenimiento',company_name:'Empresa A',description:'Experiencia en mantenimiento preventivo. Excel. Liderazgo de equipos.',external:true});
const b=D.upsertExternal({title:'Analista de operaciones',company_name:'Empresa B',description:'Análisis de datos y procesos. Excel avanzado.',external:true});
assert.equal(D.externalJobs().length,2,'no conserva múltiples ofertas externas');
D.selectExternal(a.id);assert.equal(D.selectedExternal().id,a.id,'no selecciona oferta externa');
D.setExternalStatus(a.id,'preparing');assert.equal(D.selectedExternal().status,'preparing','no actualiza estado externo');
const pack1={coverage_summary:{mandatory_total:3,mandatory_documented:1,mandatory_partial:1,missing:1},composition:{summary:'Base',source:{name:'cv1.pdf'}},focused:{related:[],transferable:[],other:[]},intro_message:'Mensaje',evidence_ledger:[{requirement:'Mantenimiento',status:'documented',evidence:'Mantenimiento preventivo',evidence_source_label:'Experiencia'},{requirement:'Excel',status:'partial',evidence:'Excel',evidence_source_label:'Competencia'},{requirement:'Liderazgo',status:'missing'}],interview:[{requirement:'Mantenimiento'}],ats_keywords:['Mantenimiento']};
const r1=D.saveVersion(a,pack1,{source_cv:'cv1.pdf'});assert(r1.created,'no creó primera versión');
const same=D.saveVersion(a,pack1,{source_cv:'cv1.pdf'});assert.equal(same.created,false,'duplica una versión idéntica');
const pack2=structuredClone(pack1);pack2.coverage_summary={mandatory_total:3,mandatory_documented:2,mandatory_partial:1,missing:0};pack2.evidence_ledger[2]={requirement:'Liderazgo',status:'documented',evidence:'Coordinación de equipo',evidence_source_label:'Experiencia'};
const r2=D.saveVersion(a,pack2,{source_cv:'cv2.pdf'});assert(r2.created,'no creó segunda versión');
const d=D.dossier(a.id);assert.equal(d.versions.length,2,'historial de versiones incorrecto');
const diff=D.diffVersions(d.versions[1],d.versions[0]);assert.equal(diff.documented_delta,1,'diff de cobertura incorrecto');assert(diff.source_changed,'no detectó cambio de CV fuente');assert(diff.newly_documented.includes('Liderazgo'),'no detectó nueva evidencia');
const ready=D.readiness(pack2);assert.equal(ready.missing,0);assert(['ready','review'].includes(ready.level));
console.log(JSON.stringify({ok:true,external_jobs:D.externalJobs().length,versions:d.versions.length,diff,readiness:ready},null,2));
