import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const read=p=>fs.readFileSync(path.join(root,p),'utf8');
function walk(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);}const js=walk(path.join(root,'assets','js')).filter(x=>x.endsWith('.js')).concat(path.join(root,'sw.js'));for(const f of js){const r=spawnSync(process.execPath,['--check',f],{encoding:'utf8'});assert.equal(r.status,0,`${f}: ${r.stderr}`)}
const index=read('index.html'),sw=read('sw.js'),loader=read('assets/js/core/module-loader-v33.js'),router=read('assets/js/core/talent-router-v38.js'),view=read('assets/views/talent.html'),dossier=read('assets/js/modules/talent/application-dossier-v46.js'),proc=read('assets/js/modules/talent/application-processes-v46.js'),agent=read('assets/js/modules/agents/talent-agent-v46.js');
assert(index.includes('<meta name="lutmin-version" content="46.0">'));assert(index.includes('?v=46.0'));assert(sw.includes("const VERSION='46.0'"));assert(sw.includes('lutmin-runtime-v46-0'));
assert(loader.includes("dossier46:'assets/js/modules/talent/application-dossier-v46.js'"));assert(loader.includes("processes46:'assets/js/modules/talent/application-processes-v46.js'"));assert(loader.includes("talentAgent46:'assets/js/modules/agents/talent-agent-v46.js'"));assert(loader.includes("applications:new Set([F.dossier46,F.processes46])"),'Mis procesos no está desacoplado de superplatform');assert(!loader.match(/applications:new Set\(\[[^\]]*F\.super/));assert(loader.includes("agent:new Set([F.dossier46,F.talentAgent46])"));assert(loader.includes('ensureTalentAgentEngine'),'Agente no expone motor de personalización lazy');
assert(view.includes('>Mis procesos</button>'));assert(view.includes('data-talent-module-panel="applications"'));assert(router.includes('LutminProcessesV46?.render?.()'));
assert(dossier.includes('nextAction')&&dossier.includes('updateProcessMeta')&&dossier.includes('processTimeline'));assert(proc.includes('PRÓXIMA ACCIÓN')&&proc.includes('downloadCalendar')&&proc.includes('Plan de seguimiento'));assert(agent.includes('data-agent-v46-processes')&&agent.includes('window.LutminAgentV46'));
const ids=[];for(const f of ['index.html',...walk(path.join(root,'assets','views')).filter(x=>x.endsWith('.html')).map(x=>path.relative(root,x))]){for(const m of read(f).matchAll(/\bid="([^"]+)"/g))ids.push([m[1],f]);}const seen=new Map();for(const [id,f] of ids){if(!seen.has(id))seen.set(id,[]);seen.get(id).push(f)}const dup=[...seen].filter(([,v])=>v.length>1);assert.equal(dup.length,0,JSON.stringify(dup.slice(0,10)));
const refs=new Set();for(const f of ['index.html','sw.js','assets/js/core/module-loader-v33.js','assets/js/core/view-loader-v32.js'])for(const m of read(f).matchAll(/(?:\.\/)?(assets\/[A-Za-z0-9_./-]+\.(?:js|css|html))/g))refs.add(m[1]);for(const r of refs)assert(fs.existsSync(path.join(root,r)),`ruta faltante ${r}`);
const fMap={};for(const m of loader.matchAll(/^\s*([A-Za-z][A-Za-z0-9]*):'([^']+\.js)'/gm))fMap[m[1]]=m[2];const appLine=loader.match(/applications:new Set\(\[([^\]]+)\]\)/)?.[1]||'';const keys=[...appLine.matchAll(/F\.([A-Za-z0-9]+)/g)].map(m=>m[1]);const bytes=keys.reduce((n,k)=>n+(fMap[k]?fs.statSync(path.join(root,fMap[k])).size:0),0);assert(bytes<45000,`Mis procesos supera 45KB: ${bytes}`);const agentLine=loader.match(/agent:new Set\(\[([^\]]+)\]\)/)?.[1]||'';const agentKeys=[...agentLine.matchAll(/F\.([A-Za-z0-9]+)/g)].map(m=>m[1]);const agentBytes=agentKeys.reduce((n,k)=>n+(fMap[k]?fs.statSync(path.join(root,fMap[k])).size:0),0);assert(agentBytes<105000,`Agente shell supera 105KB: ${agentBytes}`);
console.log(JSON.stringify({ok:true,version:'46.0',js_checked:js.length,ids:seen.size,routes:refs.size,process_runtime_bytes:bytes,process_runtime_scripts:keys.length,agent_shell_bytes:agentBytes,agent_shell_scripts:agentKeys.length},null,2));
